apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: simkeu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: simkeu-auth:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: auth-secret
