apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
  namespace: simkeu
type: Opaque
stringData:
  POSTGRES_USER: simkeu
  POSTGRES_PASSWORD: supersecurepassword
  POSTGRES_DB: simkeu
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  JWT_SECRET: fa814aa8880fd13b72fc568618a8e339146546ae9c24c91e66ee35d360dd9584
