events {}

http {
    server {
        listen 80;
        server_name _;

        location /auth/ {
            proxy_pass http://auth:8080/;
        }

        location /blockchain/ {
            proxy_pass http://blockchain:8080/;
        }

        location /debitur/ {
            proxy_pass http://debitur:8080/;
        }

        location /log/ {
            proxy_pass http://log:8080/;
        }

        location /master/ {
            proxy_pass http://master:8080/;
        }

        location /payment/ {
            proxy_pass http://payment:8080/;
        }

        location /piutang/ {
            proxy_pass http://piutang:8080/;
        }

        location /realisasi/ {
            proxy_pass http://realisasi:8080/;
        }

        location /tagihan/ {
            proxy_pass http://tagihan:8080/;
        }
    }
}